name: altayebat_app
description: تطبيق زبون أسواق الطيبات
publish_to: "none"
version: 0.2.0+2

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: 2.17.2
  provider: 6.1.5+1
  intl: 0.20.3
  cupertino_icons: 1.0.8
  url_launcher: 6.3.2
  geolocator: 14.0.3
  flutter_map: 8.3.2
  latlong2: 0.10.1
  mobile_scanner: 7.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0

flutter:
  uses-material-design: true
