create table if not exists public.app_events (
  id bigint generated by default as identity primary key,
  store_id uuid not null references public.stores(id) on delete cascade,
  customer_id uuid,
  session_id text,
  event_name text not null,
  entity_type text,
  entity_id text,
  properties jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint app_events_event_name_check check (char_length(event_name) between 1 and 80),
  constraint app_events_entity_type_check check (entity_type is null or char_length(entity_type) <= 40),
  constraint app_events_entity_id_check check (entity_id is null or char_length(entity_id) <= 160)
);

create index if not exists app_events_store_created_idx
  on public.app_events(store_id, created_at desc);
create index if not exists app_events_customer_created_idx
  on public.app_events(customer_id, created_at desc)
  where customer_id is not null;
create index if not exists app_events_entity_idx
  on public.app_events(store_id, entity_type, entity_id, event_name, created_at desc);

alter table public.app_events enable row level security;

revoke all on table public.app_events from public, anon;
grant insert on table public.app_events to authenticated;
grant select on table public.app_events to authenticated;

drop policy if exists "Customers insert own app events" on public.app_events;
create policy "Customers insert own app events"
on public.app_events for insert to authenticated
with check (
  customer_id = auth.uid()
  and exists (
    select 1 from public.stores s
    where s.id = store_id and s.is_active = true
  )
);

drop policy if exists "Store admins view app events" on public.app_events;
create policy "Store admins view app events"
on public.app_events for select to authenticated
using (private.is_store_admin(store_id));

create or replace function public.track_app_event(
  p_store_id uuid,
  p_event_name text,
  p_entity_type text default null,
  p_entity_id text default null,
  p_properties jsonb default '{}'::jsonb,
  p_session_id text default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_id bigint;
begin
  if v_uid is null then
    raise exception 'AUTH_REQUIRED' using errcode='42501';
  end if;
  if coalesce(char_length(btrim(p_event_name)),0) = 0 then
    raise exception 'INVALID_EVENT_NAME' using errcode='22023';
  end if;
  if not exists(select 1 from public.stores s where s.id=p_store_id and s.is_active=true) then
    raise exception 'STORE_UNAVAILABLE' using errcode='22023';
  end if;

  insert into public.app_events(
    store_id,customer_id,session_id,event_name,entity_type,entity_id,properties
  ) values (
    p_store_id,v_uid,nullif(btrim(p_session_id),''),left(btrim(p_event_name),80),
    nullif(left(btrim(p_entity_type),40),''),nullif(left(btrim(p_entity_id),160),''),
    coalesce(p_properties,'{}'::jsonb)
  ) returning id into v_id;
  return v_id;
end;
$$;

revoke all on function public.track_app_event(uuid,text,text,text,jsonb,text) from public, anon;
grant execute on function public.track_app_event(uuid,text,text,text,jsonb,text) to authenticated;

create or replace function public.admin_ad_performance(
  p_store_id uuid,
  p_days integer default 30
)
returns table(
  banner_id uuid,
  title text,
  impressions bigint,
  clicks bigint,
  ctr_percent numeric
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null or not private.is_store_admin(p_store_id) then
    raise exception 'FORBIDDEN' using errcode='42501';
  end if;

  return query
  select
    b.id,
    b.title,
    count(*) filter (where e.event_name='ad_impression')::bigint as impressions,
    count(*) filter (where e.event_name='ad_click')::bigint as clicks,
    case
      when count(*) filter (where e.event_name='ad_impression') = 0 then 0::numeric
      else round(
        100.0 * count(*) filter (where e.event_name='ad_click')::numeric /
        count(*) filter (where e.event_name='ad_impression')::numeric,
        2
      )
    end as ctr_percent
  from public.storefront_banners b
  left join public.app_events e
    on e.store_id=b.store_id
   and e.entity_type='sponsored_banner'
   and e.entity_id=b.id::text
   and e.created_at >= now() - make_interval(days => greatest(1,least(coalesce(p_days,30),365)))
  where b.store_id=p_store_id and b.position='sponsor'
  group by b.id,b.title,b.sort_order
  order by b.sort_order,b.id;
end;
$$;

revoke all on function public.admin_ad_performance(uuid,integer) from public, anon;
grant execute on function public.admin_ad_performance(uuid,integer) to authenticated;
