alter table public.products alter column price type numeric(14,6) using price::numeric(14,6);
alter table public.order_items alter column unit_price type numeric(14,6) using unit_price::numeric(14,6);
alter table public.products add column if not exists sale_type text not null default 'piece', add column if not exists base_unit text not null default 'piece', add column if not exists inventory_scale integer not null default 1, add column if not exists price_per_unit numeric(14,6), add column if not exists min_qty integer not null default 1, add column if not exists qty_step integer not null default 1, add column if not exists allow_amount_purchase boolean not null default false;
update public.products set price_per_unit = price where price_per_unit is null;
alter table public.products alter column price_per_unit set not null;
alter table public.products drop constraint if exists products_sale_type_check;
alter table public.products add constraint products_sale_type_check check (sale_type in ('piece','weight','volume'));
alter table public.products drop constraint if exists products_base_unit_check;
alter table public.products add constraint products_base_unit_check check (base_unit in ('piece','kg','liter'));
alter table public.products drop constraint if exists products_inventory_scale_check;
alter table public.products add constraint products_inventory_scale_check check (inventory_scale in (1,1000));
alter table public.products drop constraint if exists products_measured_shape_check;
alter table public.products add constraint products_measured_shape_check check ((sale_type='piece' and base_unit='piece' and inventory_scale=1) or (sale_type='weight' and base_unit='kg' and inventory_scale=1000) or (sale_type='volume' and base_unit='liter' and inventory_scale=1000));
alter table public.products drop constraint if exists products_qty_rules_check;
alter table public.products add constraint products_qty_rules_check check (price_per_unit > 0 and min_qty > 0 and qty_step > 0 and stock_qty >= 0 and (sale_type <> 'piece' or allow_amount_purchase = false));
alter table public.order_items add column if not exists sale_type_snapshot text not null default 'piece', add column if not exists base_unit_snapshot text not null default 'piece', add column if not exists inventory_scale_snapshot integer not null default 1, add column if not exists display_unit_price_snapshot numeric(14,6);
create index if not exists idx_products_store_sale_type on public.products (store_id, sale_type);
