create table if not exists public.ops_alerts (
  id bigint generated by default as identity primary key,
  store_id uuid not null references public.stores(id) on delete cascade,
  alert_type text not null,
  severity text not null default 'warning' check (severity in ('info','warning','critical')),
  title text not null,
  message text not null,
  entity_type text,
  entity_id text,
  dedupe_key text,
  status text not null default 'open' check (status in ('open','acknowledged','resolved')),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz
);

create unique index if not exists ops_alerts_store_dedupe_uidx
  on public.ops_alerts(store_id,dedupe_key)
  where dedupe_key is not null;
create index if not exists ops_alerts_open_idx
  on public.ops_alerts(store_id,status,created_at desc);

alter table public.ops_alerts enable row level security;
revoke all on public.ops_alerts from anon, authenticated;

create table if not exists public.automation_reports (
  id bigint generated by default as identity primary key,
  store_id uuid not null references public.stores(id) on delete cascade,
  report_type text not null,
  period_start timestamptz not null,
  period_end timestamptz not null,
  summary jsonb not null default '{}'::jsonb,
  generated_by text not null default 'n8n',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(store_id,report_type,period_start,period_end)
);
create index if not exists automation_reports_store_type_idx
  on public.automation_reports(store_id,report_type,period_end desc);
alter table public.automation_reports enable row level security;
revoke all on public.automation_reports from anon, authenticated;

alter table public.store_automation_config
  add column if not exists delivery_gps_stale_seconds integer not null default 120,
  add column if not exists delivery_late_grace_minutes integer not null default 10,
  add column if not exists payment_pending_alert_minutes integer not null default 15,
  add column if not exists product_report_days integer not null default 30,
  add column if not exists weekly_report_enabled boolean not null default true;

create or replace function public.n8n_upsert_ops_alert(
  p_store_id uuid,
  p_alert_type text,
  p_severity text,
  p_title text,
  p_message text,
  p_entity_type text default null,
  p_entity_id text default null,
  p_dedupe_key text default null,
  p_payload jsonb default '{}'::jsonb
) returns bigint
language plpgsql
security definer
set search_path='public','pg_temp'
as $$
declare v_id bigint;
begin
  if p_severity not in ('info','warning','critical') then
    raise exception 'INVALID_SEVERITY';
  end if;

  insert into public.ops_alerts(
    store_id,alert_type,severity,title,message,entity_type,entity_id,dedupe_key,payload,status,updated_at
  ) values (
    p_store_id,p_alert_type,p_severity,p_title,p_message,p_entity_type,p_entity_id,p_dedupe_key,coalesce(p_payload,'{}'::jsonb),'open',now()
  )
  on conflict (store_id,dedupe_key) where dedupe_key is not null
  do update set
    alert_type=excluded.alert_type,
    severity=excluded.severity,
    title=excluded.title,
    message=excluded.message,
    entity_type=excluded.entity_type,
    entity_id=excluded.entity_id,
    payload=excluded.payload,
    status='open',
    resolved_at=null,
    updated_at=now()
  returning id into v_id;

  return v_id;
end;
$$;

create or replace function public.n8n_save_report(
  p_store_id uuid,
  p_report_type text,
  p_period_start timestamptz,
  p_period_end timestamptz,
  p_summary jsonb
) returns bigint
language plpgsql
security definer
set search_path='public','pg_temp'
as $$
declare v_id bigint;
begin
  insert into public.automation_reports(store_id,report_type,period_start,period_end,summary,generated_by,updated_at)
  values(p_store_id,p_report_type,p_period_start,p_period_end,coalesce(p_summary,'{}'::jsonb),'n8n',now())
  on conflict(store_id,report_type,period_start,period_end)
  do update set summary=excluded.summary,generated_by='n8n',updated_at=now()
  returning id into v_id;
  return v_id;
end;
$$;

create or replace function public.n8n_low_stock_payload(p_store_id uuid)
returns jsonb
language sql
security definer
set search_path='public','pg_temp'
as $$
  select jsonb_build_object(
    'store_id',p_store_id,
    'generated_at',now(),
    'items',coalesce(jsonb_agg(jsonb_build_object(
      'product_id',p.id,
      'name',p.name,
      'stock_qty',coalesce(p.stock_qty,0),
      'threshold',coalesce(p.low_stock_threshold,c.low_stock_threshold,5),
      'is_available',p.is_available,
      'barcode',p.barcode,
      'sku',p.sku
    ) order by coalesce(p.stock_qty,0),p.name) filter (where p.id is not null),'[]'::jsonb)
  )
  from public.products p
  left join public.store_automation_config c on c.store_id=p.store_id
  where p.store_id=p_store_id
    and coalesce(p.stock_qty,0)<=coalesce(p.low_stock_threshold,c.low_stock_threshold,5);
$$;

create or replace function public.n8n_delayed_orders_payload(p_store_id uuid)
returns jsonb
language sql
security definer
set search_path='public','pg_temp'
as $$
  with cfg as (
    select coalesce(order_pending_alert_minutes,10) pending_mins,
           coalesce(order_preparing_alert_minutes,25) preparing_mins
    from public.store_automation_config where store_id=p_store_id
  ), q as (
    select o.id,o.status,o.total,o.payment_method,o.payment_status,o.created_at,
           coalesce((select max(h.created_at) from public.order_status_history h where h.order_id=o.id and h.status=o.status),o.updated_at,o.created_at) status_since,
           extract(epoch from (now()-coalesce((select max(h.created_at) from public.order_status_history h where h.order_id=o.id and h.status=o.status),o.updated_at,o.created_at)))/60.0 as minutes_in_status
    from public.orders o,cfg
    where o.store_id=p_store_id
      and ((o.status in ('pending','confirmed') and coalesce((select max(h.created_at) from public.order_status_history h where h.order_id=o.id and h.status=o.status),o.updated_at,o.created_at)<=now()-make_interval(mins=>cfg.pending_mins))
        or (o.status='preparing' and coalesce((select max(h.created_at) from public.order_status_history h where h.order_id=o.id and h.status=o.status),o.updated_at,o.created_at)<=now()-make_interval(mins=>cfg.preparing_mins)))
  )
  select jsonb_build_object('store_id',p_store_id,'generated_at',now(),
    'items',coalesce(jsonb_agg(jsonb_build_object(
      'order_id',id,'status',status,'total',total,'payment_method',payment_method,'payment_status',payment_status,
      'created_at',created_at,'status_since',status_since,'minutes_in_status',round(minutes_in_status::numeric,1)
    ) order by minutes_in_status desc),'[]'::jsonb))
  from q;
$$;

create or replace function public.n8n_delivery_health_payload(p_store_id uuid)
returns jsonb
language sql
security definer
set search_path='public','pg_temp'
as $$
  with cfg as (
    select coalesce(delivery_gps_stale_seconds,120) stale_secs,
           coalesce(delivery_late_grace_minutes,10) late_grace
    from public.store_automation_config where store_id=p_store_id
  ), q as (
    select o.id,o.driver_id,d.name driver_name,d.phone driver_phone,o.total,o.created_at,
      coalesce((select max(h.created_at) from public.order_status_history h where h.order_id=o.id and h.status='out_for_delivery'),o.updated_at,o.created_at) delivery_started_at,
      o.delivery_eta_max_minutes,
      dl.lat,dl.lng,coalesce(dl.recorded_at,dl.updated_at) last_location_at,
      extract(epoch from (now()-coalesce(dl.recorded_at,dl.updated_at))) as gps_age_seconds,
      extract(epoch from (now()-coalesce((select max(h.created_at) from public.order_status_history h where h.order_id=o.id and h.status='out_for_delivery'),o.updated_at,o.created_at)))/60.0 as delivery_minutes,
      cfg.stale_secs,cfg.late_grace
    from public.orders o
    left join public.drivers d on d.id=o.driver_id
    left join lateral (
      select x.* from public.driver_locations x where x.order_id=o.id order by coalesce(x.recorded_at,x.updated_at) desc limit 1
    ) dl on true
    cross join cfg
    where o.store_id=p_store_id and o.status='out_for_delivery'
  )
  select jsonb_build_object('store_id',p_store_id,'generated_at',now(),
    'items',coalesce(jsonb_agg(jsonb_build_object(
      'order_id',id,'driver_id',driver_id,'driver_name',driver_name,'driver_phone',driver_phone,'total',total,
      'delivery_started_at',delivery_started_at,'delivery_eta_max_minutes',delivery_eta_max_minutes,
      'last_location_at',last_location_at,'lat',lat,'lng',lng,
      'gps_age_seconds',case when last_location_at is null then null else round(gps_age_seconds::numeric,0) end,
      'delivery_minutes',round(delivery_minutes::numeric,1),
      'missing_gps',last_location_at is null,
      'stale_gps',last_location_at is null or gps_age_seconds>stale_secs,
      'late_delivery',delivery_minutes>(coalesce(delivery_eta_max_minutes,60)+late_grace)
    ) order by delivery_started_at),'[]'::jsonb))
  from q;
$$;

create or replace function public.n8n_product_intelligence_payload(p_store_id uuid,p_days integer default 30)
returns jsonb
language sql
security definer
set search_path='public','pg_temp'
as $$
  with bounds as (
    select greatest(1,least(coalesce(p_days,30),365))::int days
  ), sales as (
    select oi.product_id,sum(oi.quantity)::bigint qty_sold,sum(oi.subtotal)::numeric revenue,max(o.created_at) last_sale_at
    from public.order_items oi
    join public.orders o on o.id=oi.order_id
    cross join bounds b
    where o.store_id=p_store_id and o.status='delivered' and o.created_at>=now()-make_interval(days=>b.days)
    group by oi.product_id
  ), base as (
    select p.id,p.name,p.stock_qty,p.is_available,p.price,p.category_id,c.name category_name,
           coalesce(s.qty_sold,0) qty_sold,coalesce(s.revenue,0) revenue,s.last_sale_at,
           coalesce(p.low_stock_threshold,ac.low_stock_threshold,5) threshold
    from public.products p
    left join sales s on s.product_id=p.id
    left join public.categories c on c.id=p.category_id
    left join public.store_automation_config ac on ac.store_id=p.store_id
    where p.store_id=p_store_id
  )
  select jsonb_build_object(
    'store_id',p_store_id,'generated_at',now(),'days',(select days from bounds),
    'top_products',coalesce((select jsonb_agg(to_jsonb(x)) from (select id product_id,name,category_name,qty_sold,revenue,last_sale_at from base order by qty_sold desc,revenue desc limit 15) x),'[]'::jsonb),
    'slow_products',coalesce((select jsonb_agg(to_jsonb(x)) from (select id product_id,name,stock_qty,price,qty_sold,revenue,last_sale_at from base where is_available=true order by qty_sold asc,stock_qty desc,name limit 25) x),'[]'::jsonb),
    'no_sales',coalesce((select jsonb_agg(jsonb_build_object('product_id',id,'name',name,'stock_qty',stock_qty,'price',price)) from base where is_available=true and qty_sold=0),'[]'::jsonb),
    'low_stock',coalesce((select jsonb_agg(jsonb_build_object('product_id',id,'name',name,'stock_qty',stock_qty,'threshold',threshold)) from base where coalesce(stock_qty,0)<=threshold),'[]'::jsonb),
    'out_of_stock',coalesce((select jsonb_agg(jsonb_build_object('product_id',id,'name',name)) from base where coalesce(stock_qty,0)<=0),'[]'::jsonb)
  );
$$;

create or replace function public.n8n_payment_reconciliation_payload(p_store_id uuid)
returns jsonb
language sql
security definer
set search_path='public','pg_temp'
as $$
  with cfg as (
    select coalesce(payment_pending_alert_minutes,15) pending_mins
    from public.store_automation_config where store_id=p_store_id
  ), q as (
    select o.id,o.status,o.total,o.payment_method,o.payment_status,o.payment_reference,o.created_at,o.updated_at,
      extract(epoch from (now()-o.created_at))/60.0 age_minutes,
      case
        when o.payment_method='card' and o.payment_status='pending' and o.created_at<=now()-make_interval(mins=>cfg.pending_mins) then 'CARD_PENDING_TOO_LONG'
        when o.payment_method='card' and o.payment_status='paid' and nullif(o.payment_reference,'') is null then 'PAID_WITHOUT_REFERENCE'
        when o.payment_method='cliq' and o.payment_status='pending' and o.created_at<=now()-interval '60 minutes' then 'CLIQ_PENDING_REVIEW'
        else null
      end reason
    from public.orders o cross join cfg
    where o.store_id=p_store_id and o.status not in ('cancelled','delivered')
  )
  select jsonb_build_object('store_id',p_store_id,'generated_at',now(),
    'items',coalesce(jsonb_agg(jsonb_build_object(
      'order_id',id,'status',status,'total',total,'payment_method',payment_method,'payment_status',payment_status,
      'payment_reference',payment_reference,'created_at',created_at,'updated_at',updated_at,'age_minutes',round(age_minutes::numeric,1),'reason',reason
    ) order by created_at) filter(where reason is not null),'[]'::jsonb))
  from q;
$$;

create or replace function public.n8n_weekly_management_payload(p_store_id uuid)
returns jsonb
language sql
security definer
set search_path='public','pg_temp'
as $$
  with cfg as (
    select coalesce(timezone,'Asia/Amman') tz from public.store_automation_config where store_id=p_store_id
  ), bounds as (
    select ((now() at time zone tz)::date-6)::timestamp at time zone tz period_start,
           (((now() at time zone tz)::date+1)::timestamp at time zone tz) period_end
    from cfg
  ), ord as (
    select o.* from public.orders o,bounds b where o.store_id=p_store_id and o.created_at>=b.period_start and o.created_at<b.period_end
  ), metrics as (
    select count(*) orders_count,
      count(*) filter(where status='delivered') delivered_count,
      count(*) filter(where status='cancelled') cancelled_count,
      count(*) filter(where status not in ('delivered','cancelled')) open_count,
      coalesce(sum(total) filter(where status='delivered'),0)::numeric delivered_revenue,
      coalesce(avg(total) filter(where status='delivered'),0)::numeric avg_order_value,
      count(*) filter(where payment_method='cash') cash_orders,
      count(*) filter(where payment_method='cliq') cliq_orders,
      count(*) filter(where payment_method='card') card_orders,
      count(*) filter(where payment_status='pending') payment_pending_count
    from ord
  ), tops as (
    select oi.product_id,oi.product_name,sum(oi.quantity)::bigint quantity_sold,sum(oi.subtotal)::numeric revenue
    from public.order_items oi join ord o on o.id=oi.order_id
    where o.status='delivered'
    group by oi.product_id,oi.product_name order by quantity_sold desc,revenue desc limit 10
  )
  select jsonb_build_object(
    'store_id',p_store_id,'generated_at',now(),
    'period_start',(select period_start from bounds),'period_end',(select period_end from bounds),
    'metrics',(select to_jsonb(metrics) from metrics),
    'top_products',coalesce((select jsonb_agg(to_jsonb(tops)) from tops),'[]'::jsonb),
    'low_stock_count',(select count(*) from public.products p left join public.store_automation_config c on c.store_id=p.store_id where p.store_id=p_store_id and coalesce(p.stock_qty,0)<=coalesce(p.low_stock_threshold,c.low_stock_threshold,5)),
    'out_of_stock_count',(select count(*) from public.products p where p.store_id=p_store_id and coalesce(p.stock_qty,0)<=0),
    'active_delivery_count',(select count(*) from public.orders o where o.store_id=p_store_id and o.status='out_for_delivery')
  );
$$;

revoke all on function public.n8n_upsert_ops_alert(uuid,text,text,text,text,text,text,text,jsonb) from public,anon,authenticated;
revoke all on function public.n8n_save_report(uuid,text,timestamptz,timestamptz,jsonb) from public,anon,authenticated;
revoke all on function public.n8n_low_stock_payload(uuid) from public,anon,authenticated;
revoke all on function public.n8n_delayed_orders_payload(uuid) from public,anon,authenticated;
revoke all on function public.n8n_delivery_health_payload(uuid) from public,anon,authenticated;
revoke all on function public.n8n_product_intelligence_payload(uuid,integer) from public,anon,authenticated;
revoke all on function public.n8n_payment_reconciliation_payload(uuid) from public,anon,authenticated;
revoke all on function public.n8n_weekly_management_payload(uuid) from public,anon,authenticated;

grant execute on function public.n8n_upsert_ops_alert(uuid,text,text,text,text,text,text,text,jsonb) to service_role;
grant execute on function public.n8n_save_report(uuid,text,timestamptz,timestamptz,jsonb) to service_role;
grant execute on function public.n8n_low_stock_payload(uuid) to service_role;
grant execute on function public.n8n_delayed_orders_payload(uuid) to service_role;
grant execute on function public.n8n_delivery_health_payload(uuid) to service_role;
grant execute on function public.n8n_product_intelligence_payload(uuid,integer) to service_role;
grant execute on function public.n8n_payment_reconciliation_payload(uuid) to service_role;
grant execute on function public.n8n_weekly_management_payload(uuid) to service_role;

grant select,insert,update on public.ops_alerts to service_role;
grant select,insert,update on public.automation_reports to service_role;
